### ISSUE TITLE
Improve pattern matching

### ISSUE THREAD

**Issue by benjajaja** [rickyspanish8/adribot#1]
https://github.com/rickyspanish8/adribot/blob/7aa2a0ad03506874847ae9af5cfd2d3741e0fafb/adri.py#L28

Chaining more and more boolean conditionals is not sustainable.
Instead, use something like the `in` operator, e.g.:
```python
question_marks = ['?', '??', .......]
if text in question_marks:
```

**Comment by rickyspanish8** [comment]
thanks. solved.
